"""Phase 10.11 (card t_f884b9cd) — ``fsrs_cards.id`` autoincrement contract.

The Phase 0 baseline migration (``ca03ee90afb6_baseline_words_examples_verb_``)
declares ``fsrs_cards.id`` as ``INTEGER NOT NULL PRIMARY KEY``. SQLite
treats that declaration as a rowid alias (auto-incrementing on
INSERT), but Postgres treats it as a plain ``integer NOT NULL`` with
no autoincrement. A fresh row INSERT without an explicit ``id`` would
therefore fail on Postgres with ``NotNullViolation: null value in
column "id" of relation "fsrs_cards" violates not-null constraint``.

The Phase 10.11 ``10a2_fsrs_cards_id_identity`` migration rebinds the
column to a Postgres-managed sequence via ``GENERATED BY DEFAULT AS
IDENTITY`` (the SQL-standard form, not the legacy ``SERIAL``
keyword). On SQLite the migration is a no-op (``INTEGER PRIMARY KEY``
is already rowid-aliased).

This test pins the contract: on either dialect, inserting a new
``FsrsCard`` row without an explicit ``id`` must succeed and assign a
non-NULL ``id``.
"""
from __future__ import annotations

import secrets

import pytest

from app import database, models


@pytest.fixture
def sqlite_db_path(tmp_path, monkeypatch):
    """Fresh temp SQLite DB + JWT secret. Mirrors the conftest
    pattern used by ``test_cloze.py``, ``test_phrase_pairs_schema.py``
    etc. (each file declares its own; the conftest at the repo root
    is intentionally thin so the tests are self-contained).
    """
    db_path = tmp_path / "test_fsrs_id_autoinc.db"
    monkeypatch.setenv("DATABASE_URL", f"sqlite:///{db_path}")
    monkeypatch.setenv("LEXORA_DECKS_DIR", str(tmp_path / "decks"))
    monkeypatch.setenv("JWT_SECRET", secrets.token_hex(32))
    return db_path


@pytest.fixture
def db_session(sqlite_db_path):
    """A SQLAlchemy session for the per-test SQLite DB. Mirrors the
    pattern in ``test_cloze.py``: reconfigure the engine to point at
    the temp DB, ``create_all`` to apply the SA-level schema (the
    Phase 10.11 IDENTITY migration is dialect-specific to Postgres
    and is a no-op on SQLite — the rowid alias makes SQLite work
    natively).
    """
    from sqlalchemy.orm import sessionmaker

    database.reconfigure_for_test(f"sqlite:///{sqlite_db_path}")
    database.Base.metadata.create_all(bind=database.engine)
    SessionLocal = sessionmaker(bind=database.engine)
    with SessionLocal() as session:
        yield session


def test_fsrs_cards_insert_without_explicit_id_succeeds(db_session) -> None:
    """INSERT a fresh ``FsrsCard`` row without specifying ``id``.

    The column must autoincrement (or rowid-alias) on both SQLite
    and Postgres. The Phase 10.11 ``10a2_fsrs_cards_id_identity``
    migration rebinds ``fsrs_cards.id`` to a Postgres sequence;
    on SQLite the column is already a rowid alias.

    Pin: a fresh insert with no explicit ``id`` succeeds AND the
    persisted row carries a non-NULL ``id``. The card's
    ``exercise_type`` defaults to ``"cloze"`` (the Phase 9.1 server
    default) and ``state`` to ``1`` (FSRS Learning).
    """
    card = models.FsrsCard(
        # ``id`` deliberately omitted — must autoincrement on
        # both dialects.
        word_id=None,  # nullable on the baseline schema; doesn't
                       # matter for the autoincrement contract.
        difficulty=None,
        stability=None,
        retrievability=None,
        due_date=None,
        last_review=None,
        reps=0,
        lapses=0,
        state=1,
        elapsed_days=0,
        scheduled_days=0,
    )
    db_session.add(card)
    db_session.commit()

    assert card.id is not None, (
        "fsrs_cards.id autoincrement failed — INSERT returned a "
        "row with NULL id. On Postgres this is the NotNullViolation "
        "the Phase 10.11 10a2_fsrs_cards_id_identity migration fixes."
    )
    assert card.id > 0, (
        f"fsrs_cards.id should be a positive integer, got {card.id}"
    )


def test_fsrs_cards_insert_with_explicit_id_still_succeeds(db_session) -> None:
    """The migration uses ``BY DEFAULT`` (not ``ALWAYS``), so callers
    that explicitly set ``id`` can still do so.

    Pin: existing seed paths that read ``id`` explicitly from a
    fixture (e.g. ``app/bootstrap.py::_insert_batch``) keep working.
    The migration does not impose ``ALWAYS`` semantics — the seed
    corpus path is preserved across the upgrade.
    """
    card = models.FsrsCard(
        id=999_999,  # explicit; reserved range unlikely to collide
        word_id=None,
        difficulty=None,
        stability=None,
        retrievability=None,
        due_date=None,
        last_review=None,
        reps=0,
        lapses=0,
        state=1,
        elapsed_days=0,
        scheduled_days=0,
    )
    db_session.add(card)
    db_session.commit()

    assert card.id == 999_999, (
        "fsrs_cards.id explicit insert failed — the migration "
        "should use BY DEFAULT, not ALWAYS, semantics."
    )