"""fsrs_cards.id autoincrement on Postgres (Phase 10.11, card t_f884b9cd)

Revision ID: 10a2_fsrs_cards_id_identity
Revises: 10a1_phrase_pairs_table
Create Date: 2026-07-07 22:30:00.000000

Phase 10.11 (card t_f884b9cd) — fold-reconcile step that
surfaces a Type-04 portability defect in the ``fsrs_cards.id``
column. The Phase 0 baseline DDL declares the column as
``id INTEGER NOT NULL PRIMARY KEY`` — SQLite treats that
declaration as a rowid alias (auto-incrementing on INSERT),
but Postgres treats it as a plain ``integer NOT NULL`` with
no autoincrement. A fresh row INSERT without an explicit
``id`` therefore fails on Postgres with
``NotNullViolation: null value in column "id" of relation
"fsrs_cards" violates not-null constraint``.

## Why this matters now

The fold's DoD criterion (card body, item 5) requires
"live-smoke passes with all 5 exercise types (cloze,
matching, comprehension, idiom, phrase_match)". The literal-
widening 4→5 fix (the Apollo-flagged defect) is necessary
but not sufficient — when the live smoke ran against the
fold-ceremony backend, **all 5** ``/exercises/grade`` calls
returned ``HTTP 500 fsrs_card_vanished`` instead of
``HTTP 200``. The 500 is the existing race-condition
fallback in ``_grade_one`` masking a deeper NotNullViolation
on the FsrsCard INSERT.

The bug pre-dates Phase 10.11. The shipped SQLite corpus
seeds the ``fsrs_cards`` table with explicit ``id`` values
(per ``app/bootstrap.py::_insert_batch`` which reads the
``id`` column verbatim), so the SQLite-only test suite never
surfaces the missing autoincrement. The Phase 0/5/6/8 code
paths that CREATED new FsrsCard rows never had to round-trip
on Postgres (the existing ``fsrs_cards`` table is seeded
empty; runtime inserts only happened in tests). Phase 10.11's
literal-widening is the first fold-ceremony step that
exercises the live-Postgres ``_grade_one`` INSERT path, so
the bug surfaces here for the first time.

## Why an ``IDENTITY`` and not a ``SERIAL``

Postgres 10+ deprecated the ``SERIAL`` keyword in favour of
the SQL-standard ``GENERATED BY DEFAULT AS IDENTITY``. The
latter is portable to a hypothetical future move to
SQL-standard dialects (CockroachDB, Yugabyte, AWS Aurora PG);
the former is Postgres-specific. The live deployment runs
Postgres 16, which fully supports the ``IDENTITY`` form.

## What this migration does

On Postgres, the migration runs:

    ALTER TABLE fsrs_cards
        ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

This binds the column to a Postgres-managed sequence
(``fsrs_cards_id_seq``, auto-named) that auto-populates on
INSERT. ``BY DEFAULT`` (not ``ALWAYS``) preserves the
ability to insert explicit ``id`` values when callers want
to — the seed corpus path that reads explicit ``id`` values
from the SQLite dump still works (the seed reads the
``id`` column explicitly; without ``BY DEFAULT`` the
``INSERT`` would fail with "cannot insert a non-DEFAULT
value into column id").

On SQLite, the migration is a clean no-op: ``INTEGER
PRIMARY KEY`` is already a rowid alias and autoincrements
natively. The dialect check short-circuits the ``ALTER``
statement on SQLite — running it would error out anyway
(SQLite doesn't support the ``GENERATED BY DEFAULT AS
IDENTITY`` DDL form).

## Idempotency

The ``inspect()``-guard pattern (mirrored from the Phase
9.1 / 7.1 / 5.2 migrations) detects whether the column
already carries an identity, and short-circuits if so.
Re-running ``upgrade head`` against an already-migrated DB
is a clean no-op.

The downgrade calls
``ALTER TABLE fsrs_cards ALTER COLUMN id DROP IDENTITY IF
EXISTS``, also dialect-guarded (no-op on SQLite). After the
drop, the column reverts to ``integer NOT NULL`` — the
pre-migration state. Test suites that exercise the
SQLite dev fallback round-trip cleanly.

## Hard rules — Alembic owns this column

Phase 7.1 (card t_96ab949e) removed
``Base.metadata.create_all`` from the ``lifespan``. The
SQLAlchemy ``FsrsCard.id`` declaration is unchanged (still
``Column(Integer, primary_key=True, index=True)``) — SA
infers ``IDENTITY`` from the live schema on Postgres at
INSERT time, so the model declaration doesn't need to
mirror the runtime column shape. Only Alembic adds the
``IDENTITY`` on a fresh Postgres DB.

The matching test
(``test_fsrs_cards_id_autoincrement.py``) exercises the
``INSERT`` path against both SQLite (already-passing) and
Postgres (now-passing) to pin the contract.
"""
from typing import Sequence, Union

from alembic import op
from sqlalchemy import inspect


# Revision identifiers, used by Alembic.
revision: str = "10a2_fsrs_cards_id_identity"
down_revision: Union[str, Sequence[str], None] = "10a1_phrase_pairs_table"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


_TABLE_NAME = "fsrs_cards"
_COLUMN_NAME = "id"


def _column_has_identity(inspector, table: str, column: str) -> bool:
    """Return True iff ``table.column`` carries a Postgres IDENTITY.

    ``inspector.get_columns`` returns ``identity`` on the
    column-info dict when the live column was declared with
    ``GENERATED [BY DEFAULT | ALWAYS] AS IDENTITY``. The
    field is a ``None`` (or absent) for plain ``integer``
    columns, and a ``{"always": bool, "on_null": ...}`` dict
    for identity columns. SQLite columns return ``None``
    here — the dialect doesn't model identity the same way.

    Cross-dialect signal: this returns True ONLY on
    Postgres-with-identity. SQLite autoincrement is
    rowid-aliased and not surfaced via this API, so the
    migration is a no-op there for the right reason (the
    column is already auto-populating via rowid).
    """
    for col in inspector.get_columns(table):
        if col["name"] != column:
            continue
        identity = col.get("identity")
        return bool(identity)
    return False


def upgrade() -> None:
    bind = op.get_bind()
    dialect_name = bind.dialect.name
    inspector = inspect(bind)

    existing_tables = set(inspector.get_table_names())
    if _TABLE_NAME not in existing_tables:
        # fsrs_cards not created yet — the baseline migration
        # (``ca03ee90afb6``) will run ahead of this one and
        # create the table. The column will be a plain
        # ``integer NOT NULL`` at that point; the next
        # ``upgrade head`` invocation will re-run this
        # migration and apply the IDENTITY binding. Same
        # pattern as the Phase 5.2 ``inspect()``-guarded
        # upgrade.
        return

    if dialect_name != "postgresql":
        # SQLite (and any non-Postgres dialect): the column
        # is rowid-aliased and autoincrements natively. The
        # ``ALTER COLUMN ... ADD GENERATED BY DEFAULT AS
        # IDENTITY`` DDL is Postgres-specific; emitting it on
        # SQLite would error out. Skip cleanly.
        return

    if _column_has_identity(inspector, _TABLE_NAME, _COLUMN_NAME):
        # Idempotency guard: re-running ``upgrade head``
        # against an already-migrated DB is a clean no-op.
        # The Phase 5.2 / 7.1 / 8.1 / 9.1 pattern.
        return

    op.execute(
        "ALTER TABLE fsrs_cards "
        "ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY"
    )


def downgrade() -> None:
    bind = op.get_bind()
    dialect_name = bind.dialect.name
    inspector = inspect(bind)

    existing_tables = set(inspector.get_table_names())
    if _TABLE_NAME not in existing_tables:
        return

    if dialect_name != "postgresql":
        # No-op on non-Postgres dialects.
        return

    if not _column_has_identity(inspector, _TABLE_NAME, _COLUMN_NAME):
        # Already downgraded — clean no-op.
        return

    # ``DROP IDENTITY IF EXISTS`` is portable to Postgres 16
    # without a separate IF EXISTS clause (the IF EXISTS is
    # part of the standard). Reverts the column to a plain
    # ``integer NOT NULL`` — pre-migration state.
    op.execute(
        "ALTER TABLE fsrs_cards "
        "ALTER COLUMN id DROP IDENTITY IF EXISTS"
    )
